/*Q2*/
PROC SQL; 
CREATE TABLE WORK.QUERY1 
AS 
SELECT H_100_TRK_INFO.year, H_100_TRK_INFO.explicit, N(H_100_TRK_INFO.Song) 
AS Song 
FROM TRACK.H_100_TRK_INFO H_100_TRK_INFO 
WHERE 
   ( H_100_TRK_INFO.explicit = 1 ) 
GROUP BY H_100_TRK_INFO.year, H_100_TRK_INFO.explicit; 
QUIT;

/*Q3*/
PROC SQL; 
CREATE TABLE WORK.QUERY1 
AS 
SELECT H_100_TRK_INFO.year, AVG(H_100_TRK_INFO.Duration_S) 
AS Duration_S 
FROM TRACK.H_100_TRK_INFO H_100_TRK_INFO 
GROUP BY H_100_TRK_INFO.year; 
QUIT;

/*4*/
PROC SQL; 
CREATE TABLE WORK.QUERY1 
AS 
SELECT H_100_TRK_INFO.Song, MAX(H_100_TRK_INFO.Duration_M) 
AS Duration_M, H_100_TRK_INFO.explicit, H_100_TRK_INFO.year 
FROM TRACK.H_100_TRK_INFO H_100_TRK_INFO 
WHERE 
   ( 
      ( H_100_TRK_INFO.explicit = 1 ) AND 
      ( H_100_TRK_INFO.year = 2016 ) 
   ) 
GROUP BY H_100_TRK_INFO.Song 
ORDER BY Duration_M DESC; 
QUIT;

/*Q5*/
PROC SQL; 
CREATE TABLE WORK.QUERY 
AS 
SELECT H_100_TRK_INFO.explicit, AVG(H_100_TRK_INFO.Duration_M) 
AS Average_duration 
FROM TRACK.H_100_TRK_INFO H_100_TRK_INFO 
GROUP BY H_100_TRK_INFO.explicit; 
QUIT;
